services:
  postgres_users:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: user_service
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d user_service"]
      interval: 3s
      timeout: 3s
      retries: 10

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  user-service:
    build: ./user-service
    env_file:
      - ./user-service/.env
    ports:
      - "8001:8001"
    depends_on:
      postgres_users:
        condition: service_healthy
      rabbitmq:
        condition: service_started
